networks:
  app-tier:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  modmail:
    image: modmail
    env_file: .env
    networks: 
      - app-tier
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
        app-tier:
            ipv4_address: 172.20.0.10

volumes:
  mongodb_data_container:
